### ISSUE TITLE
Missing file  'restore-sequences.npz'

### ISSUE THREAD

**Issue by gpaaxx** [gorgen2020/LSSDM_imputation#1]
I have imported the pemsbay data in the data directory.
After starting exe_pemsby.py there is the message "begin diffusion"
model folder: ./save/pems_validationindex0_20240926_085914/

Then there is an error message:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/LSSDM_imputation/exe_pemsbay.py", line 107, in <module>
    train_loader, valid_loader, test_loader, scaler, mean_scaler = get_dataloader(
  File "/content/gdrive/MyDrive/LSSDM_imputation/dataset_pemsbay.py", line 326, in get_dataloader
    dataset = PemsBAY_Dataset(mode="train", val_len=val_len, test_len=test_len, missing_pattern=missing_pattern,
  File "/content/gdrive/MyDrive/LSSDM_imputation/dataset_pemsbay.py", line 213, in __init__
    data_seq1 = np.load('restore-sequences.npz')['all_predicted_train']
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'restore-sequences.npz'

**Comment by gorgen2020** [comment]
Thank you very much for bringing this issue to our attention. I logged into GitHub and identified the problem: for the PeMS-Bay dataset, we mistakenly left some code commented out. I have now corrected this on GitHub.   Could you please download the updated code and try running it again? If you encounter any further issues or have any questions, feel free to reach out to me.  Thank you for your understanding.
